# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mu_teg_sim"
version = "1.0.1"
authors = [
  { name="Davide Beretta", email="mail.davide.beretta+github@gmail.com" },
]
description = "An app to simulate the device physics of micro Thermoelectric Generators"
readme = "README.md"
requires-python = ">=3.6"
keywords = ["python", "thermoelectric", "physics"]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/BerriesLab/mu-teg-sim"
"Bug Tracker" = "https://github.com/BerriesLab/mu-teg-sim/issues"

[project.scripts]
mu_teg_sim = "mu_teg_sim.cli.cli:main"

[tool.setuptools.packages.find]
include = ["mu_teg_sim*"]
